### ISSUE TITLE
Endpolls - More of an observation than a bug

### ISSUE THREAD

**Issue by ghost** [LuxGracetail/PS-Roleplaying-Bot#10]
Is it ok to have endpoll timer every 12 minute or so? Because that seems rather... really short. Clusters chat, brings OOC, stressing host, etc etc.

**Comment by LuxGracetail** [comment]
I don't get what you mean by an endpoll timer.  Please be more specific.

**Comment by ghost** [comment]
Basically, a few days ago, endpolls were happening every 12 mins. Literally. There didn't seem to be a timer on them, or said timer was really, really, fast. I don't know if this is what is intended, but having up to 5 endpolls per hour doesn't look like it is.

So basically, the time between 2 endpolls should be upped to, say, 20 minutes. It also follows Articuno's advice of having not more than 3 endpolls per hour, but eh, since every RO thinks of the problem differently...

**Comment by LuxGracetail** [comment]
Hardcoded endpoll timer has been upped to 15 as of https://github.com/LuxGracetail/PS-Roleplaying-Bot/commit/181d035048699500261add01d00ccc9788f525d4
