### ISSUE TITLE
.clearrp command?

### ISSUE THREAD

**Issue by Psychoreality** [LuxGracetail/PS-Roleplaying-Bot#11]
Perhaps adding a command to clear a roleplay from .rp that a) doesn't work once the roleplay has started and b) doesn't display voids would be a good idea. I don't know how simple it would be to implement as I can only patch together certain parts of JavaScript from what I know of Python/JavaLang, but I'm sure if anyone can do it, it could be implemented.

**Comment by LuxGracetail** [comment]
Hm.  I don't really see the point of endrp not displaying voids, but it would probably be an easy patch to endrp.  I'd like some reasoning behind the need to implement such a command.

**Comment by Psychoreality** [comment]
I have a new one. There should be a patch to Roleplaying Bot so that, instead of crashing if it doesn't find a room named AmphyRP and one named RustyRP, it bypasses the unnecessary code instead, which would allow poll commands to run on alternate Showdown servers using the bot's code.

**Comment by LuxGracetail** [comment]
Hmm, I could do that.

**Comment by LuxGracetail** [comment]
Actually, make that a new issue, please.

**Comment by LuxGracetail** [comment]
I think I've patched that now, as of https://github.com/LuxGracetail/PS-Roleplaying-Bot/commit/3c03fea90bd837fc87f402617a13cb619f14152c
