### ISSUE TITLE
Allow room voices to use .rppoll

### ISSUE THREAD

**Issue by Psychoreality** [LuxGracetail/PS-Roleplaying-Bot#14]
I don't know why this was changed. Was it because /poll is a driver+ command, or was the auto poll perms thing revoked? Either way, it causes rooms to slow down (more notably Amphy rather than Main) and is generally irritating. Even if it just comes back for Main Roleplaying, it's a feature I'd like to see return.

**Comment by LuxGracetail** [comment]
Checked with Former, all good, about to patch.

**Comment by LuxGracetail** [comment]
Done as of https://github.com/LuxGracetail/PS-Roleplaying-Bot/commit/d529961782bb162c6e5bf7702d37cb2cfa4a0bd8
