### ISSUE TITLE
.vp not stopping endpolls

### ISSUE THREAD

**Issue by ghost** [LuxGracetail/PS-Roleplaying-Bot#18]
Title. Is it intended?

**Comment by LuxGracetail** [comment]
Yes, and it's right there in .help.

http://pastebin.com/LvmU0xfq

**Comment by LuxGracetail** [comment]
Yes, and it's right there in .help.

http://pastebin.com/LvmU0xfq

**Comment by LuxGracetail** [comment]
Yes, and it's right there in .help.

http://pastebin.com/LvmU0xfq
