### ISSUE TITLE
DnD poll problem

### ISSUE THREAD

**Issue by ghost** [LuxGracetail/PS-Roleplaying-Bot#2]
Happed numerous times already, with Dungeon and Dragonites being permitted via .rppoll while running in amphyrp.

Unless this is a wanted feature, it's definitely a bug. (Like, DnD can be written so many different ways...)

**Comment by CasualGryphon** [comment]
Beat me to it.

**Comment by LuxGracetail** [comment]
Alright, same as Gryphon's.  The way I catch Parallel DnDs, line ~1160 should compensate for anything starting with "Dungeons and D" or "Dungeons 'n D", I'm not sure what's happening.  Was DnD set while the poll was being made?

**Comment by PotatoBlaster** [comment]
The RP was set as 'Dungeons and Dragonites' but wasn't started yet at that time, when the poll was made. As in, it was the RP before the poll started.

**Comment by LuxGracetail** [comment]
Quoting CasualGryphon:

http://hastebin.com/raw/mijajiriwa

http://hastebin.com/raw/bigibifaqe

Maybe fix DnD's void mess up, and make the bot less spammy when this occurs?
or just tell every moderator to write it a certain way :I

**Comment by ghost** [comment]
Question : Does the first option fixes the problem? Because I believe the 2nd is the only real one. I mean, .setrp DnD or .setrp Dungeons and Dragonites isn't gonna be too hard to ask. I know some of the staff loves to write RPs differently, but eh, that screws the bot.

**Comment by LuxGracetail** [comment]
Has anyone actually seen this recently?

**Comment by ghost** [comment]
Pff

Long ass wait, sorry. No, I don't think so. Closing issue seems ok
