### ISSUE TITLE
Bot doesn't work properly on non-official servers

### ISSUE THREAD

**Issue by limdingwen** [LuxGracetail/PS-Roleplaying-Bot#20]
This is probably due to parser.js's way of initializing this.RP. It checks if the server ID is "showdown", so it inits wrongly on private servers, such as without this.freeroamTimers. This causes the bot to crash when pausing, ending RP or checking void.

Current workaround if you're hosting the bot on a private server:
`.js this.freeroamTimeouts = {}; this.staffAnnounceEndTimeouts = {}; this.autoTimeOut = {}; this.conquestTimeouts = {}; this.conquestLockouts = {}; this.voidpoll = {}; this.RP.void = {}; this.endpollTimerSet = {};`

**Comment by LuxGracetail** [comment]
Intentional, go through me before using this on another server, please.
