### ISSUE TITLE
Poll problem

### ISSUE THREAD

**Issue by ghost** [LuxGracetail/PS-Roleplaying-Bot#6]
Hayo,

A poll problem that just happened in Amphyrp : 

 Poll ended Next RP? Ends at xx:50:28
1. Trainer (5 votes)
 28%
2. Dungeons 'n Dragonites (5 votes)
 28%
3. Conquest (8 votes)
 44%

Tiebreaker Next RP Poll
1. Conquest 
2. Dungeons 'n Dragonites 

Aka : bot does tiebreaker even if the tied things aren't winning.

**Comment by LuxGracetail** [comment]
Actually, this falls under the other thing bug that I've previously noticed in https://github.com/LuxGracetail/PS-Roleplaying-Bot/issues/4 where the bot doesn't read the last option's results.

**Comment by LuxGracetail** [comment]
Fixed, hopefully.

31eac8e16a0f17e8dd5c5c0f9faf917fa96d5732
