### ISSUE TITLE
Voidpoll issue

### ISSUE THREAD

**Issue by ghost** [LuxGracetail/PS-Roleplaying-Bot#9]
That also just happened in the chat

[11:25:46] %Vent Vanitas: .voidpoll
[11:25:46] @Roleplaying Bot: Poll Voided

 Poll ended End Poll: ends at xx:26:32
1. Continue (5 votes)
 31%
2. End (11 votes)
 69%

Aka, the poll didn't get properly voided. For information, a RP was running, but got ended BEFORE the endpoll finished. The bot didn't also launch the rppoll properly and had to be launched manually as well.

**Comment by LuxGracetail** [comment]
Voidpoll didn't actually void polls in serverside progress, now does, as of: https://github.com/LuxGracetail/PS-Roleplaying-Bot/commit/a9002fd4b05da85932c7210f075b0f38f488dd64

I'm not sure about the rest.  RPpolls cannot run in parallel with each other between rooms.

Note: Void poll and voidendpoll are now two separate commands, (Kindly suggested by Skie.)

https://github.com/LuxGracetail/PS-Roleplaying-Bot/commit/7790991039501c6a0e4a69b5a206e2f9d1a42833
